# Generated by Django 6.1 on 2026-09-02 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplemetric',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100, help_text='Вес метрики в процентах. Допустимый диапазон: 70–130%.', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
