# Generated by Django 6.1 on 2026-09-02 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_couplemetric_importance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplemetric',
            name='importance',
        ),
        migrations.CreateModel(
            name='MetricImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveSmallIntegerField(default=100, help_text='Индивидуальная важность метрики в процентах. Допустимый диапазон: 0–200%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importance_settings', to='metrics.couplemetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_importances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metric', 'user'), name='unique_metric_importance_per_user')],
            },
        ),
    ]
